/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthStatusRouteImport } from './routes/api/auth/status'
import { Route as ApiRunsActivityIdRouteImport } from './routes/api/runs/$activityId'
import { Route as ApiRunsBulkRouteImport } from './routes/api/runs/bulk'
import { Route as ApiRunsLatestRouteImport } from './routes/api/runs/latest'
import { Route as ApiRunsRecentRouteImport } from './routes/api/runs/recent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStatusRoute = ApiAuthStatusRouteImport.update({
  id: '/api/auth/status',
  path: '/api/auth/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsActivityIdRoute = ApiRunsActivityIdRouteImport.update({
  id: '/api/runs/$activityId',
  path: '/api/runs/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsBulkRoute = ApiRunsBulkRouteImport.update({
  id: '/api/runs/bulk',
  path: '/api/runs/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsLatestRoute = ApiRunsLatestRouteImport.update({
  id: '/api/runs/latest',
  path: '/api/runs/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRecentRoute = ApiRunsRecentRouteImport.update({
  id: '/api/runs/recent',
  path: '/api/runs/recent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/runs/$activityId': typeof ApiRunsActivityIdRoute
  '/api/runs/bulk': typeof ApiRunsBulkRoute
  '/api/runs/latest': typeof ApiRunsLatestRoute
  '/api/runs/recent': typeof ApiRunsRecentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/runs/$activityId': typeof ApiRunsActivityIdRoute
  '/api/runs/bulk': typeof ApiRunsBulkRoute
  '/api/runs/latest': typeof ApiRunsLatestRoute
  '/api/runs/recent': typeof ApiRunsRecentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/runs/$activityId': typeof ApiRunsActivityIdRoute
  '/api/runs/bulk': typeof ApiRunsBulkRoute
  '/api/runs/latest': typeof ApiRunsLatestRoute
  '/api/runs/recent': typeof ApiRunsRecentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/status'
    | '/api/runs/$activityId'
    | '/api/runs/bulk'
    | '/api/runs/latest'
    | '/api/runs/recent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/status'
    | '/api/runs/$activityId'
    | '/api/runs/bulk'
    | '/api/runs/latest'
    | '/api/runs/recent'
  id:
    | '__root__'
    | '/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/status'
    | '/api/runs/$activityId'
    | '/api/runs/bulk'
    | '/api/runs/latest'
    | '/api/runs/recent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthStatusRoute: typeof ApiAuthStatusRoute
  ApiRunsActivityIdRoute: typeof ApiRunsActivityIdRoute
  ApiRunsBulkRoute: typeof ApiRunsBulkRoute
  ApiRunsLatestRoute: typeof ApiRunsLatestRoute
  ApiRunsRecentRoute: typeof ApiRunsRecentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/status': {
      id: '/api/auth/status'
      path: '/api/auth/status'
      fullPath: '/api/auth/status'
      preLoaderRoute: typeof ApiAuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$activityId': {
      id: '/api/runs/$activityId'
      path: '/api/runs/$activityId'
      fullPath: '/api/runs/$activityId'
      preLoaderRoute: typeof ApiRunsActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/bulk': {
      id: '/api/runs/bulk'
      path: '/api/runs/bulk'
      fullPath: '/api/runs/bulk'
      preLoaderRoute: typeof ApiRunsBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/latest': {
      id: '/api/runs/latest'
      path: '/api/runs/latest'
      fullPath: '/api/runs/latest'
      preLoaderRoute: typeof ApiRunsLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/recent': {
      id: '/api/runs/recent'
      path: '/api/runs/recent'
      fullPath: '/api/runs/recent'
      preLoaderRoute: typeof ApiRunsRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthStatusRoute: ApiAuthStatusRoute,
  ApiRunsActivityIdRoute: ApiRunsActivityIdRoute,
  ApiRunsBulkRoute: ApiRunsBulkRoute,
  ApiRunsLatestRoute: ApiRunsLatestRoute,
  ApiRunsRecentRoute: ApiRunsRecentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
